/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a81adcce-79d8-4302-970b-dac3b47e04a8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Pk26nmN30",
    "aws_user_pools_web_client_id": "442hppcu9fn2t8ga76l2bbeuo7",
    "oauth": {}
};

export default awsmobile;